import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthInitializer } from "@/components/auth-initializer";
import MainFooter from "@/components/layouts/main-footer";
import MainHeader from "@/components/layouts/main-header";
import { QueryProvider } from "@/components/providers/query-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthInitializer />
        <QueryProvider>
          <MainHeader />
          <main className="min-h-screen bg-background flex flex-col items-center justify-center">
            {children}
          </main>
          <MainFooter />
        </QueryProvider>
      </body>
    </html>
  );
}
