version: '3.8'
services:
  db:
    image: postgres:16
    container_name: postgres_pta
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development
    volumes:
      - db-store:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg-isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-store: